# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  exectr:
    docker:
      - image: cerebro/cache-ci:0.1
jobs:
  build:
    executor: exectr
    steps:
      - checkout
      - run:
          name: Download thirdparty
          command: |
            dev/download-thirdparty.sh
      - run:
          name: Setup cmake and build artifacts
          command: |
            mkdir -p build/debug
            cd build/debug
            cmake -H../.. -B.
            make
      - persist_to_workspace:
          root: .
          paths: build
  test:
    executor: exectr
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Execute Tests
          command: |
            cd build/debug
            make test
      - store_test_results:
          path: build
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
